const text= `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Egestas sed tempus urna et pharetra pharetra massa massa ultricies. Quam pellentesque nec nam aliquam sem. Sodales ut etiam sit amet nisl purus in mollis nunc. Blandit volutpat maecenas volutpat blandit aliquam. Quis varius quam quisque id diam vel quam elementum pulvinar. Sodales ut etiam sit amet nisl. Lorem dolor sed viverra ipsum nunc aliquet. Eu facilisis sed odio morbi. In mollis nunc sed id semper risus in hendrerit gravida. Non diam phasellus vestibulum lorem sed. Fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate sapien. In pellentesque massa placerat duis ultricies. Ultrices sagittis orci a scelerisque purus. Dignissim convallis aenean et tortor at risus. Ac turpis egestas maecenas pharetra convallis posuere.

Lectus nulla at volutpat diam ut venenatis. Mauris pharetra et ultrices neque ornare aenean euismod elementum nisi. Fringilla phasellus faucibus scelerisque eleifend donec pretium. Eu nisl nunc mi ipsum faucibus vitae aliquet. Facilisi nullam vehicula ipsum a arcu cursus. Viverra vitae congue eu consequat ac felis. Dui vivamus arcu felis bibendum. Nullam non nisi est sit amet facilisis. Gravida dictum fusce ut placerat. Sem et tortor consequat id porta nibh venenatis cras sed.

Euismod in pellentesque massa placerat duis ultricies lacus. Gravida cum sociis natoque penatibus et magnis dis. Nec tincidunt praesent semper feugiat nibh sed pulvinar proin gravida. Habitant morbi tristique senectus et netus et. Tortor vitae purus faucibus ornare suspendisse sed nisi lacus. Felis eget velit aliquet sagittis. Sed vulputate odio ut enim. Varius vel pharetra vel turpis nunc eget lorem. Libero enim sed faucibus turpis in eu mi bibendum neque. Suspendisse sed nisi lacus sed viverra tellus. Vitae tortor condimentum lacinia quis vel. Ut placerat orci nulla pellentesque dignissim enim sit. Tempor orci dapibus ultrices in iaculis nunc sed augue lacus.

Aliquam sem et tortor consequat id porta nibh venenatis cras. Tellus cras adipiscing enim eu turpis. Ligula ullamcorper malesuada proin libero nunc consequat interdum varius sit. Ipsum faucibus vitae aliquet nec ullamcorper sit amet risus nullam. Hendrerit dolor magna eget est lorem ipsum dolor sit. Eget mi proin sed libero enim sed faucibus turpis in. Leo vel orci porta non pulvinar neque laoreet suspendisse interdum. Donec enim diam vulputate ut pharetra sit. Eget egestas purus viverra accumsan. Pellentesque nec nam aliquam sem et tortor consequat id. Tristique magna sit amet purus gravida quis blandit turpis cursus. Facilisi cras fermentum odio eu feugiat pretium nibh ipsum. Amet est placerat in egestas. Arcu cursus vitae congue mauris rhoncus aenean. Sed velit dignissim sodales ut. Nisi porta lorem mollis aliquam ut porttitor leo a diam.

Molestie ac feugiat sed lectus vestibulum mattis ullamcorper velit sed. Pellentesque massa placerat duis ultricies. Erat imperdiet sed euismod nisi porta lorem mollis aliquam ut. Fermentum et sollicitudin ac orci phasellus egestas tellus rutrum. Faucibus nisl tincidunt eget nullam non nisi. Orci phasellus egestas tellus rutrum tellus pellentesque eu tincidunt tortor. Purus ut faucibus pulvinar elementum. Hendrerit dolor magna eget est. Enim diam vulputate ut pharetra sit amet. Velit laoreet id donec ultrices tincidunt. Non curabitur gravida arcu ac tortor dignissim.

Nec tincidunt praesent semper feugiat nibh sed pulvinar proin. Nulla at volutpat diam ut venenatis tellus. Turpis egestas integer eget aliquet nibh praesent. Elit at imperdiet dui accumsan sit amet. Volutpat lacus laoreet non curabitur gravida. Consectetur a erat nam at lectus. Ornare arcu odio ut sem nulla pharetra diam. Mi in nulla posuere sollicitudin aliquam ultrices sagittis orci. Duis ut diam quam nulla porttitor massa id neque aliquam. Vel facilisis volutpat est velit. Elit ut aliquam purus sit amet luctus venenatis. Sit amet justo donec enim diam. Mattis aliquam faucibus purus in massa. Quis commodo odio aenean sed. Pulvinar mattis nunc sed blandit libero. Id ornare arcu odio ut. Duis ultricies lacus sed turpis. Arcu cursus euismod quis viverra nibh.

Duis convallis convallis tellus id interdum velit laoreet. Elit sed vulputate mi sit amet mauris commodo quis. Semper eget duis at tellus at urna condimentum mattis pellentesque. Volutpat sed cras ornare arcu dui vivamus. Hac habitasse platea dictumst quisque sagittis purus. Lectus arcu bibendum at varius vel. Quis lectus nulla at volutpat diam ut venenatis tellus. Facilisi nullam vehicula ipsum a arcu cursus vitae congue mauris. Ac auctor augue mauris augue neque. Felis bibendum ut tristique et. Cursus metus aliquam eleifend mi in nulla. Ultrices vitae auctor eu augue ut lectus arcu. Purus semper eget duis at tellus at urna condimentum mattis. Sit amet purus gravida quis blandit. Scelerisque eleifend donec pretium vulputate sapien nec.

Odio eu feugiat pretium nibh. Ullamcorper a lacus vestibulum sed arcu non. Facilisi cras fermentum odio eu. Vulputate dignissim suspendisse in est ante in nibh mauris cursus. Euismod elementum nisi quis eleifend quam. Non nisi est sit amet. Diam vel quam elementum pulvinar etiam non quam lacus. Egestas egestas fringilla phasellus faucibus scelerisque eleifend donec pretium. Scelerisque purus semper eget duis. Tincidunt id aliquet risus feugiat. Ultrices eros in cursus turpis massa tincidunt dui. Neque volutpat ac tincidunt vitae. Eu sem integer vitae justo eget magna. Velit aliquet sagittis id consectetur purus ut faucibus pulvinar elementum. Nascetur ridiculus mus mauris vitae ultricies leo integer malesuada nunc. In egestas erat imperdiet sed euismod nisi. Felis eget velit aliquet sagittis id consectetur.

Sed elementum tempus egestas sed sed risus. Duis ut diam quam nulla porttitor massa id neque aliquam. Pulvinar elementum integer enim neque volutpat ac tincidunt. Interdum velit laoreet id donec ultrices tincidunt. Eget arcu dictum varius duis at. Turpis egestas pretium aenean pharetra magna ac. Quis vel eros donec ac. Ultricies mi quis hendrerit dolor. Urna id volutpat lacus laoreet non curabitur. Felis donec et odio pellentesque diam. Sit amet mattis vulputate enim. Vestibulum lectus mauris ultrices eros in cursus turpis massa tincidunt. Condimentum mattis pellentesque id nibh tortor id aliquet lectus. Tortor posuere ac ut consequat semper viverra. Augue neque gravida in fermentum et sollicitudin ac. Amet dictum sit amet justo.

Nisl pretium fusce id velit ut tortor. Vulputate odio ut enim blandit volutpat. Eget egestas purus viverra accumsan. Mi ipsum faucibus vitae aliquet nec. Laoreet sit amet cursus sit amet dictum sit amet. Commodo nulla facilisi nullam vehicula ipsum a arcu cursus vitae. Nibh praesent tristique magna sit. Vitae congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque. Purus in mollis nunc sed id semper risus in. Enim facilisis gravida neque convallis a. Sit amet purus gravida quis blandit. Viverra justo nec ultrices dui sapien eget mi. Bibendum at varius vel pharetra vel. Mauris sit amet massa vitae tortor condimentum lacinia quis vel. Turpis massa sed elementum tempus egestas sed sed risus. Vel orci porta non pulvinar neque laoreet. Lobortis elementum nibh tellus molestie nunc non blandit massa. Pretium nibh ipsum consequat nisl vel.

Sed risus ultricies tristique nulla aliquet enim tortor at auctor. Elit duis tristique sollicitudin nibh sit amet commodo. Dignissim cras tincidunt lobortis feugiat vivamus at augue eget arcu. Vitae congue eu consequat ac felis. Felis imperdiet proin fermentum leo vel. Eu non diam phasellus vestibulum lorem sed risus. Quis eleifend quam adipiscing vitae proin. Pellentesque eu tincidunt tortor aliquam nulla facilisi cras fermentum odio. Integer eget aliquet nibh praesent tristique magna. Adipiscing enim eu turpis egestas pretium aenean pharetra.

Praesent semper feugiat nibh sed. Viverra aliquet eget sit amet tellus cras. Amet porttitor eget dolor morbi. Nunc eget lorem dolor sed viverra ipsum nunc aliquet. Amet mattis vulputate enim nulla aliquet porttitor lacus. Vitae aliquet nec ullamcorper sit. Ultricies mi quis hendrerit dolor. Urna et pharetra pharetra massa massa. Magna sit amet purus gravida quis blandit turpis cursus. Turpis massa tincidunt dui ut ornare lectus sit amet est. Adipiscing vitae proin sagittis nisl rhoncus mattis. Amet mauris commodo quis imperdiet massa tincidunt nunc. Convallis posuere morbi leo urna molestie at elementum. Nisl pretium fusce id velit ut tortor pretium viverra suspendisse. Ullamcorper sit amet risus nullam eget felis. Auctor elit sed vulputate mi sit.

Ut pharetra sit amet aliquam id. Enim blandit volutpat maecenas volutpat blandit aliquam etiam erat velit. Ut sem viverra aliquet eget sit amet tellus cras. Cum sociis natoque penatibus et magnis dis. Eu consequat ac felis donec. Sed lectus vestibulum mattis ullamcorper velit sed. Orci sagittis eu volutpat odio facilisis mauris. Sit amet consectetur adipiscing elit. Ligula ullamcorper malesuada proin libero nunc consequat interdum varius sit. Justo laoreet sit amet cursus sit. Pellentesque habitant morbi tristique senectus et netus et malesuada.

Quis varius quam quisque id diam vel quam elementum pulvinar. Id venenatis a condimentum vitae sapien pellentesque habitant morbi tristique. Mi proin sed libero enim sed faucibus turpis in. Et tortor at risus viverra adipiscing. Sit amet nisl purus in mollis. Nisl purus in mollis nunc sed id semper risus. Faucibus purus in massa tempor nec feugiat nisl pretium fusce. Aliquam ut porttitor leo a diam sollicitudin tempor. Lobortis scelerisque fermentum dui faucibus in ornare. Senectus et netus et malesuada. Mi proin sed libero enim sed faucibus. Sed pulvinar proin gravida hendrerit. Tellus at urna condimentum mattis pellentesque id nibh tortor id.

Sed lectus vestibulum mattis ullamcorper velit sed. In nulla posuere sollicitudin aliquam ultrices sagittis orci a. At urna condimentum mattis pellentesque id nibh. Vulputate mi sit amet mauris commodo quis imperdiet massa. Enim sit amet venenatis urna cursus eget nunc scelerisque. Auctor neque vitae tempus quam pellentesque nec nam aliquam. Eu turpis egestas pretium aenean pharetra magna ac. Sed enim ut sem viverra aliquet. Id aliquet lectus proin nibh. Eget mi proin sed libero enim sed faucibus turpis. Tristique magna sit amet purus gravida. Urna neque viverra justo nec ultrices dui sapien eget mi. Amet luctus venenatis lectus magna fringilla urna. Sed id semper risus in hendrerit gravida rutrum quisque non. Pharetra vel turpis nunc eget lorem dolor sed viverra ipsum.`;

export default text;